[build.environment]
  NETLIFY_USE_PNPM = "true"
  NODE_VERSION = "16"
  NODE_OPTIONS = "--max_old_space_size=4096"

[build]
  publish = "dist"
  command = "pnpm -w run deploy"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/play/*"
  to = "/play/index.html"
  status = 200

[[redirects]]
  from = "https://unocss.antfu.me/*"
  to = "https://uno.antfu.me/play/:splat"
  status = 302
  force = true
